(()=>{'use strict';
const W=Math.max(2,+new URLSearchParams(location.search).get('week')||2),L='1392257124943282176',A='https://api.sleeper.app/v1';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),f=(n,d=2)=>Number(n||0).toFixed(d),roman=n=>['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII'][n]||n;
const F={1:['The Peasants of Troy','Joey Neptune','#ff8700','West'],2:['TroyisBetterthanOdyssey','Bonnie Neptune','#f000e8','West'],3:['🏺Hades Nutz','Bernard Laguerre','#7a7a7a','West'],4:['Winged Victory Formation','Courtney Quintero','#087b32','East'],5:["Apollo's Archers",'Mike Quintero','#1263bd','East'],6:['Hercules Unchained','Asim Conrad','#e30613','West'],7:['Flight of JarYES','Mike Jarnot','#7414df','East'],8:['Uranus Colonizer','Twaine Gordon','#633632','East'],9:['The Beer of Olympus','Charles Bryant','#7dca36','East'],10:['BeginnersRuck','Tomiwa Adetoyese-Olagunju','#7180a4','East'],11:['Winging It','Kerrmit Strachan','#9a7a00','West'],12:['Aries It Out','Tyler Meglan','#13bfdf','West']};
try{mapPaused=true}catch(_){};
const bad=/^(FreshPrinceNeptune|PrincessNeptune|MikeTheMarauder|TwaineG|Deltboyhuck|JohnnyKickbutt|Mertik242|Meggleberries)$/i,meta={};let baseDataPromise=null,playersPromise=null,refreshing=false;
const style=document.createElement('style');style.textContent='.dynLoad{padding:35px;text-align:center;font:700 13px Arial;color:#6f4808}.dynLegend{display:grid;grid-template-columns:70px 1fr;gap:8px;padding:10px;border:2px solid #58442f;border-left:6px solid var(--a);margin:7px 0;background:#fff}.dynLegend .p{font-size:28px;font-weight:900;color:#21170f}.dynLegend small{display:block;color:var(--a);font:800 11px Arial}.dynDiv{margin:8px 0}.dynDiv h3{margin:0;padding:7px 9px;background:#261b13;color:#fff8e8;font:900 10px Arial;text-transform:uppercase}.dynSnap{display:grid;grid-template-columns:1fr 1fr;gap:6px}.dynSnap>div{display:grid;grid-template-columns:25px 1fr auto;gap:6px;padding:7px 8px;border:1px solid #d7c8ad;border-left:4px solid var(--a);font:700 11px Arial;background:#fff}.dynClimb{height:500px;background:#071822}.dynClimb iframe{width:100%;height:100%;border:0}.mapEnlarge{position:absolute;right:8px;top:8px;z-index:30;width:32px;height:32px}.dynSub{margin-top:5px;color:#6f4808;font:800 11px Arial}@media(max-width:760px){.dynLegend{grid-template-columns:40px 1fr;padding:6px}.dynLegend .p{font-size:17px}.dynLegend small,.dynSub{font-size:7px}.dynSnap{grid-template-columns:1fr}.dynSnap>div{font-size:7px;padding:4px 6px}.dynClimb{height:auto;aspect-ratio:16/10}}';document.head.appendChild(style);
const get=async p=>{const r=await fetch(A+p,{cache:'no-store'});if(!r.ok)throw Error('Sleeper '+r.status);return r.json()},baseData=()=>baseDataPromise||(baseDataPromise=Promise.all([get(`/league/${L}/users`),get(`/league/${L}/rosters`)])),nflPlayers=()=>playersPromise||(playersPromise=get('/players/nfl')),score=r=>+(r.custom_points??r.points??0)||0,groups=rows=>{const x={};rows.forEach(r=>(x[r.matchup_id]||(x[r.matchup_id]=[])).push(r));return Object.values(x).filter(a=>a.length>1)};
function team(r){return meta[+r]||{id:+r,name:'Roster '+r,manager:'Unknown',color:'#9a6a12',division:'East'}}
function color(m){let c=m?.color||'#9a6a12',x=c.replace('#','');if(x.length!==6)return c;let r=parseInt(x.slice(0,2),16),g=parseInt(x.slice(2,4),16),b=parseInt(x.slice(4),16),l=.2126*r+.7152*g+.0722*b;if(l>180){let k=145/l;return '#'+[r,g,b].map(v=>Math.round(v*k).toString(16).padStart(2,'0')).join('')}return c}
function games(D){return groups(D.weeks[W]).map((p,i)=>{let a=p[0],b=p[1],sa=score(a),sb=score(b);return{i,a,b,sa,sb,ma:team(a.roster_id),mb:team(b.roster_id),margin:Math.abs(sa-sb),sum:sa+sb,win:sa>=sb?a:b,lose:sa>=sb?b:a}})}
function allplay(D){let a=games(D).flatMap(g=>[[g.a.roster_id,g.sa],[g.b.roster_id,g.sb]]).map(x=>({m:team(x[0]),s:x[1],w:0,l:0,t:0}));a.forEach(x=>a.forEach(y=>{if(x===y)return;x.s>y.s?x.w++:x.s<y.s?x.l++:x.t++}));return a.sort((x,y)=>y.w-x.w||y.s-x.s)}
function standings(D){let o={};Object.values(meta).forEach(m=>o[m.id]={m,w:0,l:0,t:0,pf:0});for(let w=1;w<=W;w++)groups(D.weeks[w]).forEach(p=>{let a=o[p[0].roster_id],b=o[p[1].roster_id],sa=score(p[0]),sb=score(p[1]);if(!a||!b)return;a.pf+=sa;b.pf+=sb;sa>sb?(a.w++,b.l++):sb>sa?(b.w++,a.l++):(a.t++,b.t++)});return Object.values(o).sort((a,b)=>b.w-a.w||b.pf-a.pf)}
function starters(D){let z=[];D.weeks[W].forEach(r=>(r.starters||[]).forEach(id=>{let p=D.players[id]||{},s=+(r.players_points?.[id]||0);z.push({m:team(r.roster_id),id,name:p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||id,pos:p.position||p.fantasy_positions?.[0]||'FLEX',nfl:p.team||'',s})}));return z}
function card(g,D){let a=g.ma,b=g.mb,win=team(g.win.roster_id),lose=team(g.lose.roster_id),st=starters(D),pa=st.filter(x=>x.m.id===a.id).sort((x,y)=>y.s-x.s)[0],pb=st.filter(x=>x.m.id===b.id).sort((x,y)=>y.s-x.s)[0],title=g.margin<=2?'By the Narrowest Thread':g.margin>=30?'A Rout Beneath Olympus':'The Campaign Continues';return `<section class="chronBattleCard" style="--battle-a:${color(a)}"><h2><span style="color:${color(a)}">${e(a.name)}</span> <span style="color:#6f4808">vs.</span> <span style="color:${color(b)}">${e(b.name)}</span></h2><h3>${title}</h3><p><strong>${e(a.name)} ${f(g.sa)} • ${e(b.name)} ${f(g.sb)}</strong></p><p>${e(win.name)} carried the day by <strong>${f(g.margin)} points</strong>. ${g.margin<=5?'The result stayed on a knife’s edge until the final scoring swings settled the field.':g.margin>=25?'By the end, the margin had become a warning to the rest of Olympus.':'The advantage held long enough to become another mark in the standings.'}</p><p>${pa?`<strong>${e(pa.name)}</strong> led ${e(a.name)} with ${f(pa.s,1)}. `:''}${pb?`<strong>${e(pb.name)}</strong> answered with ${f(pb.s,1)} for ${e(b.name)}.`:''}</p><p>${e(win.name)} left Week ${W} with the victory. ${e(lose.name)} left with another chapter still to write.</p></section>`}
function mapHTML(){return `<section class="section"><h2>The World Before & The World After</h2><div class="mapTitle"><b>Week ${W} Conquest</b><span>Live from the main conquest board</span></div><div class="stateMap fadeMap dynMap"><iframe class="before" src="./?chronicleEmbed=1"></iframe><iframe class="after" src="./?chronicleEmbed=1"></iframe><div class="stateBadge">Before Week ${W}</div><button class="mapEnlarge">⛶</button></div><p class="note">The map fades between the conquest state entering Week ${W} and the current state after Week ${W}.</p></section>`}
function prep(frame,w,hi){let go=()=>{try{let d=frame.contentDocument,s=d.createElement('style');s.textContent='header,.controlbar,.weekRail,.side,.sidebar,.landscapeMenuPanel,.battle-banner,.battleBanner,.battleMessage,.conquestBanner,.conquest-banner,.legend,.maptop,.footerhint,.modalBackdrop,.gmbar,.drawer,[class*=sidebar]{display:none!important}.app,.main,.mapPaneShell,.mapcard{display:block!important;width:100%!important;height:100vh!important;padding:0!important;margin:0!important}#mapSvg{width:100%!important;height:100vh!important}html,body{margin:0!important;overflow:hidden!important;background:#0c1822!important}';d.head.appendChild(s);let c=d.createElement('script');c.textContent=`try{stateThroughWeek(${w});updateMapFills();renderArmyUnits();${hi?`(history||[]).filter(e=>+e.week===${W}).forEach(e=>(e.transfers||[]).forEach(t=>{let p=pathByTerritory?.[t.territoryId];if(p){p.style.stroke='#ffd34f';p.style.strokeWidth='7'}}));`:''}}catch(e){}`;d.body.appendChild(c)}catch(_){}};frame.addEventListener('load',()=>setTimeout(go,700),{once:true});if(frame.contentDocument?.readyState==='complete')setTimeout(go,700)}
function setupMap(m){if(!m)return;let a=q('.before',m),b=q('.after',m),badge=q('.stateBadge',m),on=false;prep(a,W-1,0);prep(b,W,W);setInterval(()=>{on=!on;m.classList.toggle('showAfter',on);badge.textContent=(on?'After':'Before')+' Week '+W},4200);q('.mapEnlarge',m).onclick=()=>m.requestFullscreen?.()}
function exportConquest(frame,done){let tries=0,timer=0;const run=()=>{try{const d=frame?.contentDocument;if(!d||!d.body)throw Error('map not ready');const c=d.createElement('script');c.textContent=`try{let s=stateThroughWeek(${W}),own=s.owners||currentOwners||{};window.__chronicleDynamicConquest={teams:(teams||[]).map(t=>({id:t.id,name:t.name})),territories:(territoryDefs||[]).map(t=>({id:t.id,name:t.name,owner:own[t.id]||null})),events:(history||[]).filter(ev=>Number(ev.week)===${W}).flatMap(ev=>(ev.transfers||[]).map(x=>({territoryId:x.territoryId,from:x.fromTeamId??x.from??null,to:x.toTeamId??x.to??null})))}}catch(e){window.__chronicleDynamicConquest={error:String(e)}}`;d.body.appendChild(c);setTimeout(()=>{let x=frame.contentWindow?.__chronicleDynamicConquest;if(x&&!x.error)return done(x);if(++tries<18)timer=setTimeout(run,350)},120)}catch(_){if(++tries<18)timer=setTimeout(run,350)}};frame?.addEventListener('load',()=>setTimeout(run,850),{once:true});setTimeout(run,1000);return()=>clearTimeout(timer)}
function renderConquestData(x){if(!x)return;const tm=Object.fromEntries((x.teams||[]).map(t=>[String(t.id),t.name])),terr=Object.fromEntries((x.territories||[]).map(t=>[String(t.id),t]));const changed=q('#dynChanged');if(changed){changed.innerHTML=(x.events||[]).length?(x.events||[]).map(ev=>{const t=terr[String(ev.territoryId)],from=tm[String(ev.from)]||'Unclaimed',to=tm[String(ev.to)]||'Unknown';return `<div class="change"><b>${e(t?.name||ev.territoryId)}</b>${e(from)} → ${e(to)}</div>`}).join(''):`<div class="change"><b>Week ${W} conquest state</b>No canonical territory transfer has been posted for Week ${W} yet. The map and ledger below still reflect the main board state through Week ${W}.</div>`}const by={};(x.territories||[]).forEach(t=>{if(t.owner==null)return;(by[String(t.owner)]||(by[String(t.owner)]=[])).push(t.name)});const ledger=q('#dynLedger');if(ledger){const rows=Object.entries(by).map(([id,names])=>({name:tm[id]||id,names:names.sort((a,b)=>a.localeCompare(b))})).sort((a,b)=>a.name.localeCompare(b.name));ledger.innerHTML=rows.length?rows.map(r=>{const m=Object.values(meta).find(z=>z.name===r.name),a=color(m);return `<div class="territoryCard canonicalTerritoryCard" style="--team-accent:${a}"><div class="count">${r.names.length} territories</div><h3>${e(r.name)}</h3><div class="territoryNames">${r.names.map(n=>`<span>${e(n)}</span>`).join('')}</div></div>`}).join(''):`<div class="territoryCard">Canonical Week ${W} territory data is loading from the main board…</div>`}}

async function editorialChronicle(){
  const p=new URLSearchParams(location.search),pad=n=>String(n).padStart(2,'0');
  const mdKey='olympus-chronicle-week-'+pad(W)+'-md';
  let md='';
  if(p.get('draft')==='1')md=localStorage.getItem(mdKey)||'';
  if(!md){
    try{
      const r=await fetch('./chronicles/week-'+pad(W)+'.md?'+Date.now(),{cache:'no-store'});
      if(r.ok)md=await r.text();
    }catch(_){}
  }
  if(!md)return false;
  const esc=t=>String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const inline=t=>esc(t).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+?)\*/g,'<em>$1</em>');
  const lines=String(md).replace(/\r/g,'').split('\n'),out=[];
  for(const raw of lines){
    const t=raw.trim();
    if(!t)continue;
    if(/^###\s+/.test(t))out.push('<h3>'+inline(t.replace(/^###\s+/,''))+'</h3>');
    else if(/^##\s+/.test(t))out.push('<h2>'+inline(t.replace(/^##\s+/,''))+'</h2>');
    else if(/^#\s+/.test(t))out.push('<h1>'+inline(t.replace(/^#\s+/,''))+'</h1>');
    else out.push('<p>'+inline(t)+'</p>');
  }
  const pane=q('#chronicle');
  if(!pane)return false;
  qa(':scope > .section',pane).forEach(sec=>{
    const h=txt(q('h2',sec));
    if(/^The Chronicle/i.test(h)||/^The Six Battles/i.test(h))sec.remove();
  });
  const sec=document.createElement('section');
  sec.className='section customChronicleSection';
  sec.innerHTML='<h2>The Chronicle • Week '+W+'</h2><article class="chron richChronicle">'+out.join('')+'</article>';
  const map=qa(':scope > .section',pane).find(sec=>/The World Before/i.test(txt(q('h2',sec))));
  map?map.after(sec):pane.prepend(sec);
  if(!document.getElementById('richChronicleStyles')){
    const st=document.createElement('style');st.id='richChronicleStyles';
    st.textContent='.richChronicle h1{font-size:clamp(34px,6vw,52px);line-height:1.05;color:#6f4808;margin:0 0 18px}.richChronicle h2{font-size:clamp(26px,4vw,34px);line-height:1.15;color:#6f180f;margin:34px 0 10px}.richChronicle h3{font-size:clamp(21px,3vw,27px);line-height:1.2;color:#6f4808;margin:18px 0 10px}.richChronicle p{margin:0 0 20px}.richChronicle strong{color:#76500b}.richChronicle em{color:#5e4b3b}';
    document.head.appendChild(st);
  }
  return true;
}
function chron(D){let G=games(D),S=G.flatMap(g=>[{m:g.ma,s:g.sa},{m:g.mb,s:g.sb}]).sort((a,b)=>b.s-a.s),avg=S.reduce((n,x)=>n+x.s,0)/Math.max(1,S.length),close=[...G].sort((a,b)=>a.margin-b.margin)[0],big=[...G].sort((a,b)=>b.margin-a.margin)[0];q('#chronicle').innerHTML=`<section class="section"><h2>The Chronicle • Blood, Fortune & Fate</h2><article class="chron"><header class="chronLead"><h1>Chapter ${roman(W)} • The Week ${W} Campaign</h1></header><p>Week ${W} opened with six new wars beneath Olympus. Every score, margin, and performance in this chapter comes from the Week ${W} battlefield, with the current slate treated as the final record for this preview.</p><p>${e(S[0]?.m.name)} set the pace at <strong>${f(S[0]?.s)} points</strong>, while the league averaged <strong>${f(avg,1)}</strong>. The closest struggle came down to <strong>${f(close?.margin)} points</strong>, while the widest gap reached <strong>${f(big?.margin)}.</strong></p><p>No one yet knew which Week ${W} result would matter most when the summit finally came into view.<br>The Battle for Mount Olympus continued with six wars.</p></article></section><section class="section topScoreboard"><h2>Week ${W} Scoreboard • The Six Battles</h2><div class="scoregrid">${G.map(g=>`<div class="score"><div class="row ${g.sa>=g.sb?'win':''}"><span>${e(g.ma.name)}</span><span>${f(g.sa)}</span></div><div class="row ${g.sb>g.sa?'win':''}"><span>${e(g.mb.name)}</span><span>${f(g.sb)}</span></div><span class="note">${f(g.margin)} point margin</span></div>`).join('')}</div></section>${mapHTML()}<section class="section"><h2>The Six Battles • Week ${W}</h2><article class="chron">${G.map(g=>card(g,D)).join('')}</article></section><section class="section"><h2>The Ascent of Olympus • Week ${W}</h2><p class="note">The mountain after the Week ${W} battles.</p><div class="dynClimb"><iframe src="./?chronicleOlympus=1&week=${W}"></iframe></div></section><section class="section"><h2>Week ${W} All-Play Snapshot</h2><div class="dynSnap">${allplay(D).map((x,i)=>`<div style="--a:${color(x.m)}"><b>${i+1}</b><span>${e(x.m.name)}</span><b>${x.w}-${x.l}${x.t?'-'+x.t:''}</b></div>`).join('')}</div></section>`;setupMap(q('#chronicle .dynMap'))}
function honors(D){let G=games(D),S=G.flatMap(g=>[{m:g.ma,s:g.sa,g},{m:g.mb,s:g.sb,g}]),top=[...S].sort((a,b)=>b.s-a.s)[0],close=[...G].sort((a,b)=>a.margin-b.margin)[0],blow=[...G].sort((a,b)=>b.margin-a.margin)[0],loss=G.map(g=>({m:team(g.lose.roster_id),s:g.lose===g.a?g.sa:g.sb,g})).sort((a,b)=>b.s-a.s)[0],low=G.map(g=>({m:team(g.win.roster_id),s:g.win===g.a?g.sa:g.sb,g})).sort((a,b)=>a.s-b.s)[0],chaos=[...G].sort((a,b)=>b.sum-a.sum)[0],avg=S.reduce((n,x)=>n+x.s,0)/S.length,field=[...S].sort((a,b)=>Math.abs(a.s-avg)-Math.abs(b.s-avg))[0],ap=allplay(D)[0],C=(i,t,m,v,d,sub='')=>`<div class="honor open"><span>${i} ${t}</span><strong style="color:${color(m)}">${e(m.name)}</strong><em>${e(v)}</em>${sub?`<div class="dynSub">${e(sub)}</div>`:''}<div class="more">${e(d)}</div></div>`;q('#honorCards').innerHTML=[C('👑','High King',top.m,f(top.s)+' points','Highest score of the week.'),C('⚔️','Slaughter',team(blow.win.roster_id),f(blow.margin)+'-point victory','Largest margin.',`Defeated ${team(blow.lose.roster_id).name}.`),C('💔','Heartbreak',team(close.lose.roster_id),'Lost by '+f(close.margin),'Closest defeat.',`Lost to ${team(close.win.roster_id).name}.`),C('😭','Robbed',loss.m,f(loss.s)+' in a loss','Highest-scoring loss.'),C('🍀','Highway Robbery',low.m,'Won with '+f(low.s),'Lowest winning score.'),C('🔥','Chaos Match',chaos.ma,f(chaos.sum)+' combined','Highest combined matchup.',`${chaos.ma.name} vs. ${chaos.mb.name}.`),C('♟️','All-Play King',ap.m,`${ap.w}-${ap.l}${ap.t?'-'+ap.t:''}`,'Best against the weekly field.'),C('🎯','Closest to Field',field.m,f(Math.abs(field.s-avg),1)+' from average','Finished closest to league average.')].join('');q('#honors .section h2').textContent=`Week ${W} Honors & Superlatives`;let st=starters(D),pos=['QB','RB','WR','TE','DEF','K'];q('#honors .leaders').innerHTML=pos.map(p=>{let a=st.filter(x=>x.pos===p||(p==='DEF'&&['DST','D/ST'].includes(x.pos))).sort((x,y)=>y.s-x.s).slice(0,p==='DEF'?2:3);return `<div class="leader"><b>${p==='DEF'?'D/ST':p}</b><br>${a.map((x,i)=>`${i+1}. ${e(x.name)} • ${f(x.s,1)}`).join('<br>')||'No scored starters'}</div>`}).join('')}
function stand(D){let R=standings(D),table=a=>a.map((x,i)=>`<tr><td>${i+1}</td><td><b>${e(x.m.name)}</b></td><td class="manager">${e(x.m.manager)}</td><td>${x.w}-${x.l}${x.t?'-'+x.t:''}</td><td>${f(x.pf)}</td></tr>`).join(''),sec=qa('#standings .section')[0];sec.innerHTML=`<h2>Standings After Week ${W}</h2><p class="note">Current Week ${W} scores are treated as final for this newsletter snapshot.</p>${['West','East'].map(d=>`<div class="dynDiv"><h3>${d} Division</h3><div class="tw"><table><thead><tr><th>#</th><th>Army</th><th class="manager">Manager</th><th>Record</th><th>PF</th></tr></thead><tbody>${table(R.filter(x=>x.m.division===d))}</tbody></table></div></div>`).join('')}`;let ap=allplay(D);qa('#standings .section')[1].innerHTML=`<h2>Weekly All-Play • Strength of the Field</h2><div class="tw"><table><thead><tr><th>#</th><th>Army</th><th>Score</th><th>All-Play</th><th>%</th></tr></thead><tbody>${ap.map((x,i)=>`<tr><td>${i+1}</td><td>${e(x.m.name)}</td><td>${f(x.s)}</td><td>${x.w}-${x.l}</td><td>${((x.w+.5*x.t)/11*100).toFixed(1)}</td></tr>`).join('')}</tbody></table></div>`}
function legends(D){let a=starters(D).filter(x=>x.s>=30).sort((x,y)=>y.s-x.s),p=q('#legends'),sec=qa('.section',p)[0];qa('.section',p).slice(1).forEach(x=>x.remove());sec.innerHTML=`<h2>Hall of Living Legends • Week ${W} Inscriptions</h2>${a.length?a.map(x=>`<div class="dynLegend" style="--a:${color(x.m)}"><div class="p">${f(x.s,1)}</div><div><b>${e(x.name)}</b><small>${e(x.pos+(x.nfl?' • '+x.nfl:''))}</small><span class="note">${e(x.m.name)} • ${e(x.m.manager)}</span></div></div>`).join(''):'<div class="legend"><b>No new inscriptions yet.</b><br><span class="note">No starter has reached 30 points in the current snapshot.</span></div>'}`}
function conquest(D){let p=q('#conquest'),G=games(D),lead=[...G].sort((a,b)=>b.margin-a.margin)[0];p.innerHTML=`<section class="section"><h2>Conquest • Week ${W} Territory Report</h2><div class="battlehead"><div class="n">Week ${W} conquest snapshot</div><strong>${e(team(lead?.win?.roster_id).name||'Week '+W)}</strong><div class="territory">Scores are treated as final for this preview; canonical territory ownership is read directly from the main conquest board.</div></div>${mapHTML().replace('<section class="section">','').replace('</section>','')}<div id="dynChanged" class="changed"><div class="change"><b>Loading Week ${W} conquest changes…</b>Reading the canonical territory history from the main board.</div></div></section><section class="section"><h2>Territories Held After Week ${W}</h2><p class="note">Canonical ownership through Week ${W}, read from the main conquest board.</p><div id="dynLedger" class="ledger"><div class="territoryCard">Loading Week ${W} territory ledger…</div></div></section>`;const m=q('#conquest .dynMap');setupMap(m);exportConquest(q('.after',m),renderConquestData)}
function head(){q('.mast .ey').textContent='The League of Olympus';q('.mast h1').textContent='The Battle for Olympus';q('.mast .sub').textContent=`Chapter ${roman(W)} • Week ${W}`;q('.hero .panel')?.remove();q('.hero').style.gridTemplateColumns='1fr';q('.hero .ey').textContent=`Chapter ${roman(W)}`;q('.hero h2').textContent=W===2?'The Second Campaign of Olympus':`The Week ${W} Campaign`;q('.hero .deck').textContent=`The battles, heroes, heartbreaks, and consequences of Week ${W} entered the record.`;q('.footer').innerHTML=`<div class="ey">Thus ended Chapter ${roman(W)} of the conquest.</div><p>But the mountain remained, and the armies climbed on.</p><a href="./">Return to Present-Day Olympus</a>`}
function tabs(){qa('.tab').forEach(b=>b.onclick=()=>{qa('.tab').forEach(x=>x.classList.toggle('active',x===b));qa('.pane').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));history.replaceState(null,'','#'+b.dataset.tab)})}
async function load(){if(refreshing)return;refreshing=true;try{q('#chronicle').innerHTML=`<section class="section"><div class="dynLoad"><b>Summoning the Week ${W} Chronicle…</b><br>Reading Week ${W} Sleeper scores and statistics.</div></section>`;document.title=`League of Olympus • Week ${W} Chronicle`;let [[u,r],...ws]=await Promise.all([baseData(),...Array.from({length:W},(_,i)=>get(`/league/${L}/matchups/${i+1}`))]),ub=Object.fromEntries(u.map(x=>[x.user_id,x]));r.forEach(x=>{let ff=F[x.roster_id]||[],user=ub[x.owner_id],n=x.metadata?.team_name||user?.metadata?.team_name||user?.display_name||ff[0]||`Roster ${x.roster_id}`;if(bad.test(n))n=ff[0]||n;meta[x.roster_id]={id:x.roster_id,name:n,manager:ff[1]||user?.display_name||'Unknown',color:ff[2]||'#9a6a12',division:ff[3]||'East'}});let ids=new Set();ws[W-1].forEach(x=>{(x.starters||[]).forEach(y=>ids.add(String(y)));Object.keys(x.players_points||{}).forEach(y=>ids.add(String(y)))});let all=await nflPlayers(),players={};ids.forEach(id=>{if(all[id])players[id]=all[id]});let D={weeks:Object.fromEntries(ws.map((x,i)=>[i+1,x])),players};chron(D);await editorialChronicle();honors(D);stand(D);legends(D);conquest(D);head();tabs();window.__chronicleDynamicReady=true}finally{refreshing=false}}
load().catch(err=>{console.error(err);q('#chronicle').innerHTML=`<section class="section"><div class="dynLoad"><b>Week ${W} could not be summoned.</b><br>${e(err.message||err)}</div></section>`});setInterval(()=>load().catch(()=>{}),60000);
})();
